# Generated by Django 2.2.10 on 2021-02-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyChoicesField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple', models.BooleanField(default=False)),
                ('choices', models.ManyToManyField(to='core.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('use_choices', models.BooleanField(default=False)),
                ('choices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SurveyChoicesField')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('answ_txt', models.TextField(blank=True, null=True)),
                ('answ_choices', models.ManyToManyField(blank=True, to='core.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Survey')),
            ],
            options={
                'unique_together': {('user_id', 'question', 'survey')},
            },
        ),
    ]
